# This is a basic workflow to help you get started with Actions

name: PublishToEsoUI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
              #Folder that should live inside the zip, probably should match add-on name
              path: 'ArtaeumGroupTool'

      - name: Zip release
        #Zips the release, excluding .git* and .vscode files
        run: 7z a ArtaeumGroupTool.zip * -xr!*.git* -xr!*.vscode*
        
        
      - name: ESO UI Publish
        # uses: Xeio/esoui-deploy-action@7ee218a03aa9d59ed5e742f1dd076d8c9638a947
        uses: Xeio/esoui-deploy-action@v1.4
        with:
          # Path to the add-on declaration file to parse versioning from
          addon-file-path:  "./ArtaeumGroupTool/ArtaeumGroupTool.txt"
          # Path to zip file to upload to ESO UI as the new version
          upload-zip-path: ArtaeumGroupTool.zip
          addon-id: 3012
          eso-ui-api-key: ${{secrets.ESOUI_API_TOKEN}}
          github-api-key: ${{secrets.TOKEN_GITHUB}}
