name: PushToEsoUI

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Pushing
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'ArtaeumGroupTool'

      - name: Hello world action step
        id: hello
        uses: M0RGaming/Push-To-EsoUI@main
        with:
          who-to-greet: 'Mona the Octocat'
          EsoUIToken: ${{secrets.ESOUI_API_TOKEN}}
          EsoUIID: 3012
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
